-- Migração: 1 desafio por nível (A1/A2/B1/B2) em Ouça e traduza e Acentuação,
-- pra visualizar como as duas categorias ficam com conteúdo variado por nível
-- (Ouça e traduza só tinha A2 antes; Acentuação só tinha B1). Curadoria + TTS
-- pelo pipeline de sempre, needs_review -- passa pela revisão humana normal.

insert into public.challenges (id, type, level, status, data) values
  ('lt-a1-001', 'listen_translate', 'A1', 'needs_review', '{"sentenceFr": "Je mange une pomme.", "audioFile": "d987b47080a1.mp3", "hintText": "Je ______ une pomme.", "referenceTranslations": ["Eu como uma maçã.", "Estou comendo uma maçã.", "Eu estou a comer uma maçã."], "explanation": ""}'::jsonb),
  ('lt-a2-001', 'listen_translate', 'A2', 'needs_review', '{"sentenceFr": "J''ai acheté un nouveau livre hier soir et je l''ai déjà commencé.", "audioFile": "b52c07bde996.mp3", "hintText": "J''ai acheté ______ livre ______ et je l''ai ______ commencé.", "referenceTranslations": ["Comprei um livro novo ontem à noite e já comecei.", "Ontem à noite eu comprei um livro novo e já o iniciei.", "Comprei um livro novo ontem e já comecei a ler."], "explanation": ""}'::jsonb),
  ('lt-b1-001', 'listen_translate', 'B1', 'needs_review', '{"sentenceFr": "Hier soir, j''ai regardé un film intéressant à la télévision, mais je me suis endormi avant la fin.", "audioFile": "ec69abf9c387.mp3", "hintText": "Hier soir, j''ai regardé un film intéressant ______ la télévision, mais je me suis endormi ______ la fin.", "referenceTranslations": ["Ontem à noite, assisti a um filme interessante na televisão, mas adormeci antes do final.", "Ontem à noite, eu vi um filme interessante pela TV, porém acabei dormindo antes de terminar.", "Eu vi um filme legal na TV ontem à noite, mas peguei no sono antes do fim."], "explanation": ""}'::jsonb),
  ('lt-b2-001', 'listen_translate', 'B2', 'needs_review', '{"sentenceFr": "Même si le projet est ambitieux, nous sommes convaincus que nous parviendrons à le mener à bien grâce à la collaboration de tous.", "audioFile": "369fc1da3aba.mp3", "hintText": "______ le projet est ambitieux, nous sommes ______ que nous parviendrons à le ______ à bien ______ à la collaboration de tous.", "referenceTranslations": ["Mesmo que o projeto seja ambicioso, estamos confiantes de que conseguiremos levá-lo adiante graças à colaboração de todos.", "Ainda que o projeto seja ambicioso, temos a convicção de que seremos capazes de concluí-lo com sucesso devido à cooperação de todos.", "Conquanto o projeto seja ambicioso, estamos certos de que o finalizaremos com êxito pela colaboração geral."], "explanation": "A expressão ''mener à bien'' significa concluir com sucesso, realizar algo de forma satisfatória."}'::jsonb),
  ('accent-a1-001', 'accent', 'A1', 'needs_review', '{"targetText": "école", "audioFile": "d9bf28a92935.mp3", "explanation": "\"e\" tem acento agudo."}'::jsonb),
  ('accent-a2-001', 'accent', 'A2', 'needs_review', '{"targetText": "à bientôt", "audioFile": "3a8464fa98b7.mp3", "explanation": "\"a\" tem acento grave, \"o\" tem acento circunflexo."}'::jsonb),
  ('accent-b2-001', 'accent', 'B2', 'needs_review', '{"targetText": "préférer", "audioFile": "cb5fd48070e3.mp3", "explanation": "\"e\" tem acento agudo, \"e\" tem acento agudo."}'::jsonb)
on conflict (id) do nothing;
