-- Migração de dados: challenges.js -> tabela challenges
-- Gerado automaticamente a partir do conteúdo já existente em produção.
-- Nenhum destes desafios está publicado hoje (todos needs_review),
-- então a migração não altera o que o aluno vê.

insert into public.challenges (id, type, level, status, data) values
  ('expr-001', 'expression', 'B1', 'needs_review', '{"canonicalExpression": "avoir la gueule de bois", "expressionAudioFile": "d87557d62cf5.mp3", "meaning": {"fr": "Avoir mal à la tête et se sentir mal après avoir trop bu d''alcool.", "pt": "Sentir-se mal, ter dor de cabeça após ter bebido muito álcool."}, "example": {"text": "Hier soir, j''ai trop bu et ce matin, j''ai vraiment la gueule de bois."}, "question": "Que signifie cette expression ?", "options": ["Être très fatigué après une longue journée.", "Se sentir mal et avoir mal à la tête après avoir trop bu d''alcool.", "Avoir une mauvaise humeur passagère.", "Être surpris par une nouvelle."], "correctAnswer": "Se sentir mal et avoir mal à la tête après avoir trop bu d''alcool.", "explanation": "Cette expression décrit les symptômes physiques désagréables qui suivent une consommation excessive d''alcool.", "secondExample": {"text": "Après la fête, les étudiants avaient la gueule de bois et regrettaient leurs excès.", "audioFile": "3b1c6dda1481.mp3"}, "microActivity": {"prompt": "Il a beaucoup plu hier, alors aujourd''hui, je __________ et je ne veux pas sortir.", "answer": "ai la gueule de bois"}, "externalResources": [{"type": "article", "url": "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGz6mD55hRpawEhicDepI6tOMbyso4X2LvOZVBabU3fk8gN02G6-7RvRdlOci0hH9w5Ytk2z_UtldRPXx2pbOy9RyLWdM1swBNq_qcZfXU4-_KLtt4TIy9YWfj46u96-izIvTcZd8PFgF6aIbOLpJhKPdfcyG-X", "title": "lalanguefrancaise.com", "sourceName": "lalanguefrancaise.com", "description": "Fornece uma explicação detalhada do significado, origem, sinônimos e exemplos de uso.", "quality": "high", "buttonLabel": "En savoir plus", "approved": true, "lastChecked": null}, {"type": "youglish", "url": "https://youglish.com/pronounce/avoir%20la%20gueule%20de%20bois/french", "title": "YouGlish", "sourceName": "YouGlish", "description": "Ouça a expressão sendo usada por falantes reais em vários vídeos.", "quality": "high", "buttonLabel": "Voir en contexte", "approved": true, "lastChecked": null}]}'::jsonb),
  ('expr-002', 'expression', 'B1', 'needs_review', '{"canonicalExpression": "casser les pieds", "expressionAudioFile": "be1073fb6337.mp3", "meaning": {"fr": "C''est quand quelqu''un t''énerve ou t''ennuie beaucoup.", "pt": "Significa incomodar ou irritar muito alguém."}, "example": {"text": "Arrête de faire ce bruit, tu me casses les pieds depuis ce matin !"}, "question": "Que signifie l''expression \"casser les pieds\" ?", "options": ["Faire du bruit fort", "Être très fatigué", "Incommoder ou énerver quelqu''un", "Casser un objet"], "correctAnswer": "Incommoder ou énerver quelqu''un", "explanation": "Cette expression idiomatique signifie ennuyer ou agacer profondément quelqu''un. On l''utilise quand une personne ou une situation devient très irritante.", "secondExample": {"text": "J''ai essayé de lui expliquer la situation calmement, mais il a continué à me poser les mêmes questions, il me cassait les pieds.", "audioFile": "0ef77b5de63c.mp3"}, "microActivity": {"prompt": "Mon frère a encore oublié de faire la vaisselle, il __________ !", "answer": "me casse les pieds"}, "externalResources": [{"type": "dictionary", "url": "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFnabHsvcKme3zTwSpAflxhdx_CtdB3wElTHGpKaqzHPVppyxjpdtj8dYuqCbrHxgS4TjyVKAG5r-fRBz9oGO7dCpuViTVDO1nFe3E3JLQvMzjoZr2wYBs7E888o4gL4EDa3s9YiKJOiak=", "title": "wiktionary.org", "sourceName": "wiktionary.org", "description": "Um dicionário colaborativo que fornece definições detalhadas, etimologia e exemplos de uso para palavras e expressões.", "quality": "high", "buttonLabel": "En savoir plus", "approved": true, "lastChecked": null}, {"type": "youglish", "url": "https://youglish.com/pronounce/casser%20les%20pieds/french", "title": "YouGlish", "sourceName": "YouGlish", "description": "Ouça a expressão sendo usada por falantes reais em vários vídeos.", "quality": "high", "buttonLabel": "Voir en contexte", "approved": true, "lastChecked": null}]}'::jsonb),
  ('expr-003', 'expression', 'B1', 'needs_review', '{"canonicalExpression": "poser un lapin", "expressionAudioFile": "c27236a9a4e4.mp3", "meaning": {"fr": "Ne pas venir à un rendez-vous sans prévenir.", "pt": "Dar um bolo, não comparecer a um compromisso."}, "example": {"text": "J''étais très en colère parce que mon ami m''a posé un lapin pour notre rendez-vous hier soir."}, "question": "Que signifie cette expression ?", "options": ["Faire une blague à quelqu''un.", "Ne pas venir à un rendez-vous sans prévenir.", "Inviter quelqu''un à manger.", "Raconter une histoire drôle."], "correctAnswer": "Ne pas venir à un rendez-vous sans prévenir.", "explanation": "Cette expression signifie qu''une personne ne s''est pas présentée à un rendez-vous convenu et n''a pas donné de nouvelles.", "secondExample": {"text": "Elle a décidé de lui poser un lapin car elle ne voulait plus le voir.", "audioFile": "830e4e90cee6.mp3"}, "microActivity": {"prompt": "Il ne faut pas __________ quand on a promis de venir.", "answer": "poser de lapin"}, "externalResources": [{"type": "dictionary", "url": "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFEL8cTUf19hTff_bmYHkSuRtzLnKu5aS4RXHSB9um9dCKHd0P6Jt8SNdXBsb9hVlTbBXao6uw_3RFGpqMEO2T8g9i_JT8eeueksNfwaaKHyH5Ayrk4HZP9V8HzkwwQi2ilWRWaXNs=", "title": "wiktionary.org", "sourceName": "wiktionary.org", "description": "Dicionário com definições, etimologia e exemplos de uso da expressão.", "quality": "high", "buttonLabel": "En savoir plus", "approved": true, "lastChecked": null}, {"type": "youglish", "url": "https://youglish.com/pronounce/poser%20un%20lapin/french", "title": "YouGlish", "sourceName": "YouGlish", "description": "Ouça a expressão sendo usada por falantes reais em vários vídeos.", "quality": "high", "buttonLabel": "Voir en contexte", "approved": true, "lastChecked": null}]}'::jsonb),
  ('lt-auto-001', 'listen_translate', 'A2', 'needs_review', '{"sentenceFr": "J''ai acheté un nouveau livre hier et je l''ai déjà fini.", "audioFile": "849334555ba3.mp3", "hintText": "J''ai acheté un nouveau ______ hier et je l''ai déjà ______.", "referenceTranslations": ["Comprei um livro novo ontem e já terminei.", "Comprei um livro novo ontem e já o acabei.", "Ontem comprei um livro novo e já o terminei."], "explanation": ""}'::jsonb),
  ('lt-auto-002', 'listen_translate', 'A2', 'needs_review', '{"sentenceFr": "Ce week-end, nous allons visiter un musée dans le centre-ville.", "audioFile": "5f0f7f8e7744.mp3", "hintText": "Ce week-end, nous allons ______ un musée dans le ______.", "referenceTranslations": ["Neste fim de semana, vamos visitar um museu no centro da cidade.", "Vamos visitar um museu no centro da cidade neste fim de semana.", "O plano para este fim de semana é visitar um museu no centro."], "explanation": ""}'::jsonb),
  ('lt-auto-003', 'listen_translate', 'A2', 'needs_review', '{"sentenceFr": "Elle est un peu fatiguée parce qu''elle a beaucoup travaillé aujourd''hui.", "audioFile": "62e1501f76e8.mp3", "hintText": "Elle est un peu ______ parce qu''elle a beaucoup ______ aujourd''hui.", "referenceTranslations": ["Ela está um pouco cansada porque trabalhou muito hoje.", "Ela está um pouco exausta, pois trabalhou bastante hoje.", "Como trabalhou muito hoje, ela está um pouco cansada."], "explanation": ""}'::jsonb),
  ('accent-auto-001', 'accent', 'B1', 'needs_review', '{"targetText": "fréquent", "audioFile": "fcbc4b1eaaf6.mp3", "explanation": "\"e\" tem acento agudo."}'::jsonb),
  ('accent-auto-002', 'accent', 'B1', 'needs_review', '{"targetText": "même", "audioFile": "cd8c5826c750.mp3", "explanation": "\"e\" tem acento circunflexo."}'::jsonb),
  ('accent-auto-003', 'accent', 'B1', 'needs_review', '{"targetText": "voilà", "audioFile": "957c44c4238f.mp3", "explanation": "\"a\" tem acento grave."}'::jsonb),
  ('accent-auto-004', 'accent', 'B1', 'needs_review', '{"targetText": "déjà", "audioFile": "eb49cf71b9ac.mp3", "explanation": "\"e\" tem acento agudo, \"a\" tem acento grave."}'::jsonb),
  ('accent-auto-005', 'accent', 'B1', 'needs_review', '{"targetText": "après", "audioFile": "1b4815ffd3e4.mp3", "explanation": "\"e\" tem acento grave."}'::jsonb),
  ('accent-auto-006', 'accent', 'B1', 'needs_review', '{"targetText": "français", "audioFile": "616e89b4d5aa.mp3", "explanation": "\"c\" tem acento cedilha."}'::jsonb)
on conflict (id) do nothing;
